export const transactionOperationHistory = {
    "data": [
        {
            "TRANSACTION_ID": "8135125",
            "CREATED_TS": "1704357466",
            "UPDATED_TS": "1704357466",
            "TYPE": "INTERNAL TRANSFER",
            "TITLE": "Transfer",
            "AMOUNT": "1.00",
            "CURRENCY": "EUR",
            "UID": "xQIwwfny",
            "STATUS": "COMPLETED",
            "MESSAGE": null,
            "DESCRIPTION": null,
            "TO": "CH8708843108691721010",
            "CODE_SECURED": false,
            "FEE_AMOUNT": "0.00",
            "FEE_CURRENCY": null,
            "FROM": "CH7208843108691721280",
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "1.00",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": "1086917",
            "RECEIVER_CUSTOMER_NUMBER": "1086917"
        },
        {
            "TRANSACTION_ID": "8135124",
            "CREATED_TS": "1704357406",
            "UPDATED_TS": "1704357406",
            "TYPE": "INCOMING TRANSFER",
            "TITLE": "Transfer",
            "AMOUNT": "1.00",
            "CURRENCY": "EUR",
            "UID": "09wNCVu4",
            "STATUS": "COMPLETED",
            "MESSAGE": null,
            "DESCRIPTION": "From +37120207332",
            "TO": "CH7208843108691721280",
            "CODE_SECURED": false,
            "FEE_AMOUNT": "0.00",
            "FEE_CURRENCY": null,
            "FROM": "+37120207332",
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "1.00",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": "1404964",
            "RECEIVER_CUSTOMER_NUMBER": "1086917"
        },
        {
            "TRANSACTION_ID": "8135122",
            "CREATED_TS": "1704357344",
            "UPDATED_TS": "1704357344",
            "TYPE": "INTERNAL TRANSFER",
            "TITLE": "Transfer",
            "AMOUNT": "0.99",
            "CURRENCY": "EUR",
            "UID": "q8i9mVOm",
            "STATUS": "COMPLETED",
            "MESSAGE": null,
            "DESCRIPTION": null,
            "TO": "CH8708843108691721010",
            "CODE_SECURED": false,
            "FEE_AMOUNT": "0.00",
            "FEE_CURRENCY": null,
            "FROM": "CH7208843108691721280",
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "0.99",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": "1086917",
            "RECEIVER_CUSTOMER_NUMBER": "1086917"
        },
        {
            "TRANSACTION_ID": "8126373",
            "CREATED_TS": "1704276457",
            "UPDATED_TS": "1704276457",
            "TYPE": "OUTGOING TRANSFER",
            "TITLE": "Transfer",
            "AMOUNT": "-0.01",
            "CURRENCY": "EUR",
            "UID": "HmMoAwFh",
            "STATUS": "COMPLETED",
            "MESSAGE": null,
            "DESCRIPTION": "To +37120207332",
            "TO": "+37120207332",
            "CODE_SECURED": false,
            "FEE_AMOUNT": "0.00",
            "FEE_CURRENCY": null,
            "FROM": "CH7208843108691721280",
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "-0.01",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": "1086917",
            "RECEIVER_CUSTOMER_NUMBER": "1404964"
        },
        {
            "TRANSACTION_ID": "8126371",
            "CREATED_TS": "1704276426",
            "UPDATED_TS": "1704276426",
            "TYPE": "OUTGOING TRANSFER",
            "TITLE": "Transfer",
            "AMOUNT": "-0.01",
            "CURRENCY": "EUR",
            "UID": "p3AtDaIl",
            "STATUS": "COMPLETED",
            "MESSAGE": null,
            "DESCRIPTION": "To +37120207332",
            "TO": "+37120207332",
            "CODE_SECURED": false,
            "FEE_AMOUNT": "0.00",
            "FEE_CURRENCY": null,
            "FROM": "CH8708843108691721010",
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "-0.01",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": "1086917",
            "RECEIVER_CUSTOMER_NUMBER": "1404964"
        },
        {
            "TRANSACTION_ID": "8126366",
            "CREATED_TS": "1704276120",
            "UPDATED_TS": "1704276120",
            "TYPE": "OUTGOING TRANSFER",
            "TITLE": "Transfer",
            "AMOUNT": "-0.01",
            "CURRENCY": "EUR",
            "UID": "RSQQUOCS",
            "STATUS": "PENDING",
            "MESSAGE": null,
            "DESCRIPTION": "To +37125603405",
            "TO": "+37125603405",
            "CODE_SECURED": false,
            "FEE_AMOUNT": "0.00",
            "FEE_CURRENCY": null,
            "FROM": "CH8708843108691721010",
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "-0.01",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": "1086917",
            "RECEIVER_CUSTOMER_NUMBER": null
        },
        {
            "TRANSACTION_ID": "8126365",
            "CREATED_TS": "1704276093",
            "UPDATED_TS": "1704276093",
            "TYPE": "OUTGOING TRANSFER",
            "TITLE": "Transfer",
            "AMOUNT": "-0.01",
            "CURRENCY": "EUR",
            "UID": "WqYE0D27",
            "STATUS": "COMPLETED",
            "MESSAGE": null,
            "DESCRIPTION": "To +37120030189",
            "TO": "+37120030189",
            "CODE_SECURED": false,
            "FEE_AMOUNT": "0.00",
            "FEE_CURRENCY": null,
            "FROM": "CH8708843108691721010",
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "-0.01",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": "1086917",
            "RECEIVER_CUSTOMER_NUMBER": "1060394"
        },
        {
            "TRANSACTION_ID": "8126141",
            "CREATED_TS": "1704274132",
            "UPDATED_TS": "1704274132",
            "TYPE": "OUTGOING TRANSFER",
            "TITLE": "Transfer",
            "AMOUNT": "-0.10",
            "CURRENCY": "EUR",
            "UID": "cHXSxF1p",
            "STATUS": "COMPLETED",
            "MESSAGE": null,
            "DESCRIPTION": "To +37120207332",
            "TO": "+37120207332",
            "CODE_SECURED": false,
            "FEE_AMOUNT": "0.00",
            "FEE_CURRENCY": null,
            "FROM": "CH8708843108691721010",
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "-0.10",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": "1086917",
            "RECEIVER_CUSTOMER_NUMBER": "1404964"
        },
        {
            "TRANSACTION_ID": "8103968",
            "CREATED_TS": "1704093780",
            "UPDATED_TS": "1704093780",
            "TYPE": "COMMISSION CHARGE",
            "TITLE": "Commission",
            "AMOUNT": "-0.50",
            "CURRENCY": "CHF",
            "UID": "qYe61i6E",
            "STATUS": "COMPLETED",
            "MESSAGE": null,
            "DESCRIPTION": "Monthly fee for card 495055******7348",
            "TO": null,
            "CODE_SECURED": false,
            "FEE_AMOUNT": "0.00",
            "FEE_CURRENCY": null,
            "FROM": "CH9508843108691721060",
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "-0.54",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": "1086917",
            "RECEIVER_CUSTOMER_NUMBER": null
        },
        {
            "TRANSACTION_ID": "8103967",
            "CREATED_TS": "1704093780",
            "UPDATED_TS": "1704093780",
            "TYPE": "COMMISSION CHARGE",
            "TITLE": "Commission",
            "AMOUNT": "-0.50",
            "CURRENCY": "CHF",
            "UID": "CH5Idn3R",
            "STATUS": "COMPLETED",
            "MESSAGE": null,
            "DESCRIPTION": "Monthly fee for card 495055******2104",
            "TO": null,
            "CODE_SECURED": false,
            "FEE_AMOUNT": "0.00",
            "FEE_CURRENCY": null,
            "FROM": "CH9508843108691721060",
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "-0.54",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": "1086917",
            "RECEIVER_CUSTOMER_NUMBER": null
        },
        {
            "TRANSACTION_ID": "8103966",
            "CREATED_TS": "1704093780",
            "UPDATED_TS": "1704093780",
            "TYPE": "COMMISSION CHARGE",
            "TITLE": "Commission",
            "AMOUNT": "-0.50",
            "CURRENCY": "CHF",
            "UID": "3vd1ofYC",
            "STATUS": "COMPLETED",
            "MESSAGE": null,
            "DESCRIPTION": "Monthly fee for card 495055******4953",
            "TO": null,
            "CODE_SECURED": false,
            "FEE_AMOUNT": "0.00",
            "FEE_CURRENCY": null,
            "FROM": "CH9508843108691721060",
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "-0.54",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": "1086917",
            "RECEIVER_CUSTOMER_NUMBER": null
        },
        {
            "TRANSACTION_ID": "8097105",
            "CREATED_TS": "1704070829",
            "UPDATED_TS": "1704070829",
            "TYPE": "COMMISSION CHARGE",
            "TITLE": "Commission",
            "AMOUNT": "-1.00",
            "CURRENCY": "EUR",
            "UID": "XtEw9cXk",
            "STATUS": "COMPLETED",
            "MESSAGE": null,
            "DESCRIPTION": "Account monthly fee",
            "TO": null,
            "CODE_SECURED": false,
            "FEE_AMOUNT": "0.00",
            "FEE_CURRENCY": null,
            "FROM": "CH8708843108691721010",
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "-1.00",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": "1086917",
            "RECEIVER_CUSTOMER_NUMBER": null
        },
        {
            "TRANSACTION_ID": "8019025",
            "CREATED_TS": "1703232530",
            "UPDATED_TS": "1703232530",
            "TYPE": "OUTGOING TRANSFER",
            "TITLE": "Transfer",
            "AMOUNT": "-1.00",
            "CURRENCY": "EUR",
            "UID": "oyfI3GBf",
            "STATUS": "COMPLETED",
            "MESSAGE": "is test",
            "DESCRIPTION": "To +37120207332",
            "TO": "+37120207332",
            "CODE_SECURED": false,
            "FEE_AMOUNT": "0.00",
            "FEE_CURRENCY": null,
            "FROM": "CH8708843108691721010",
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "-1.00",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": "1086917",
            "RECEIVER_CUSTOMER_NUMBER": "1404964"
        },
        {
            "TRANSACTION_ID": "8011727",
            "CREATED_TS": "1703161528",
            "UPDATED_TS": "1703161536",
            "TYPE": "WITHDRAWAL",
            "TITLE": "Withdrawal to card",
            "AMOUNT": "-1.00",
            "CURRENCY": "EUR",
            "UID": "rr2sx87f",
            "STATUS": "COMPLETED",
            "MESSAGE": null,
            "DESCRIPTION": "4165 98** **** 8603",
            "TO": null,
            "CODE_SECURED": false,
            "FEE_AMOUNT": "0.00",
            "FEE_CURRENCY": "EUR",
            "FROM": "CH8708843108691721010",
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "-1.00",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": "1086917",
            "RECEIVER_CUSTOMER_NUMBER": null
        },
        {
            "TRANSACTION_ID": "8011674",
            "CREATED_TS": "1703161191",
            "UPDATED_TS": "1703161202",
            "TYPE": "WITHDRAWAL",
            "TITLE": "Transfer to card",
            "AMOUNT": "-1.00",
            "CURRENCY": "EUR",
            "UID": "PZywCmq7",
            "STATUS": "COMPLETED",
            "MESSAGE": null,
            "DESCRIPTION": "4950 55** **** 2104",
            "TO": null,
            "CODE_SECURED": false,
            "FEE_AMOUNT": "0.00",
            "FEE_CURRENCY": null,
            "FROM": "CH8708843108691721010",
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "-1.00",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": "1086917",
            "RECEIVER_CUSTOMER_NUMBER": null
        },
        {
            "TRANSACTION_ID": "8010860",
            "CREATED_TS": "1703153321",
            "UPDATED_TS": "1703153329",
            "TYPE": "DEPOSIT",
            "TITLE": "Transfer from card",
            "AMOUNT": "1.00",
            "CURRENCY": "EUR",
            "UID": "fQfrcdzg",
            "STATUS": "COMPLETED",
            "MESSAGE": null,
            "DESCRIPTION": "4950 55** **** 4953",
            "TO": "CH7208843108691721280",
            "CODE_SECURED": false,
            "FEE_AMOUNT": "0.00",
            "FEE_CURRENCY": null,
            "FROM": null,
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "1.00",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": null,
            "RECEIVER_CUSTOMER_NUMBER": "1086917"
        },
        {
            "TRANSACTION_ID": "7995975",
            "CREATED_TS": "1702996602",
            "UPDATED_TS": "1702996609",
            "TYPE": "WITHDRAWAL",
            "TITLE": "Western Union Withdrawal",
            "AMOUNT": "-1.04",
            "CURRENCY": "CHF",
            "UID": "91i2kTdB",
            "STATUS": "COMPLETED",
            "MESSAGE": null,
            "DESCRIPTION": "Western Union withdrawal MTCN: 2986903372",
            "TO": null,
            "CODE_SECURED": false,
            "FEE_AMOUNT": "-3.50",
            "FEE_CURRENCY": "CHF",
            "FROM": "CH8708843108691721010",
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "-1.05",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": "1086917",
            "RECEIVER_CUSTOMER_NUMBER": null
        },
        {
            "TRANSACTION_ID": "7986197",
            "CREATED_TS": "1702906125",
            "UPDATED_TS": "1702906128",
            "TYPE": "DEPOSIT",
            "TITLE": "Deposit from card",
            "AMOUNT": "10.00",
            "CURRENCY": "EUR",
            "UID": "X12zM9Tr",
            "STATUS": "COMPLETED",
            "MESSAGE": null,
            "DESCRIPTION": "4165 98** **** 8603",
            "TO": "CH8708843108691721010",
            "CODE_SECURED": false,
            "FEE_AMOUNT": "0.00",
            "FEE_CURRENCY": "EUR",
            "FROM": null,
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "10.00",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": null,
            "RECEIVER_CUSTOMER_NUMBER": "1086917"
        },
        {
            "TRANSACTION_ID": "7984883",
            "CREATED_TS": "1702896495",
            "UPDATED_TS": "1702896501",
            "TYPE": "WITHDRAWAL",
            "TITLE": "Western Union Withdrawal",
            "AMOUNT": "-1.04",
            "CURRENCY": "CHF",
            "UID": "yKAwNETS",
            "STATUS": "COMPLETED",
            "MESSAGE": null,
            "DESCRIPTION": "Western Union withdrawal MTCN: 8787067584",
            "TO": null,
            "CODE_SECURED": false,
            "FEE_AMOUNT": "-3.50",
            "FEE_CURRENCY": "CHF",
            "FROM": "CH8708843108691721010",
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "-1.05",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": "1086917",
            "RECEIVER_CUSTOMER_NUMBER": null
        },
        {
            "TRANSACTION_ID": "7984879",
            "CREATED_TS": "1702896384",
            "UPDATED_TS": "1702896386",
            "TYPE": "DEPOSIT",
            "TITLE": "Deposit from card",
            "AMOUNT": "5.00",
            "CURRENCY": "EUR",
            "UID": "CVT9mKCL",
            "STATUS": "COMPLETED",
            "MESSAGE": null,
            "DESCRIPTION": "4165 98** **** 8603",
            "TO": "CH8708843108691721010",
            "CODE_SECURED": false,
            "FEE_AMOUNT": "0.00",
            "FEE_CURRENCY": "EUR",
            "FROM": null,
            "CUSTOM_DATA": null,
            "PDF": false,
            "CONSOLIDATE_AMOUNT": "5.00",
            "CONSOLIDATE_CURRENCY": "EUR",
            "SENDER_CUSTOMER_NUMBER": null,
            "RECEIVER_CUSTOMER_NUMBER": "1086917"
        }
    ],
    "page_count": 53
}